[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
phases.setup.nixPkgs = ["python311", "gcc", "libffi"]

[deploy]
startCommand = "python ui/app_operator_nicegui.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
